### ISSUE TITLE
How to upload content with specific type

### ISSUE THREAD

**Issue by kasturisameer** [Elijah23Johnson/react-native-azure-blob-storage#10]
I tried this way, but no luck
` await EAzureBlobStorageImage.uploadFile({
            filePath: p.node.image.uri,
            contentType: "image/jpg",
            fileName: "img.jpg"
        })
`

**Comment by ammedinap93** [comment]
I tried the example code and I could upload the image to the Storage, but it was stored without its file extension.
```
let name = await EAzureBlobStorageImage.uploadFile(p.node.image.uri);
console.log('Container File Name', name);
```
![image](https://user-images.githubusercontent.com/43796884/93846711-d1875500-fc72-11ea-867e-0633d9aed169.png)

I do not see any Documentation regarding this, then I will appreciate any help.
Thanks in advance.

**Comment by hanks1981** [comment]
I have the same problem, I have followed the steps to pass the config object to it and it does not recognize it. But if you only sent the path save the image with a random name.

**Comment by Elijah23Johnson** [comment]
Open the azure container, copy the url to the container and then simply
append the random filename to the back of that url. No need for the
extension. It will defer it from the container and pick it up.

**Comment by Elijah23Johnson** [comment]
See latest version and read.me no align
