### ISSUE TITLE
can i use this package for uploading,downloading and delete blobs to azure blob storage?

### ISSUE THREAD

**Issue by Vrushabh59** [Elijah23Johnson/react-native-azure-blob-storage#11]

**Comment by Elijah23Johnson** [comment]
Yes

**Comment by Elijah23Johnson** [comment]
What is your use case?

**Comment by Vrushabh59** [comment]
upload & download image,video and pdf and stream video from blob storage and if needed than delete blob from app , i had already done uploading & downloading

**Comment by Elijah23Johnson** [comment]
Just so I understand you... You are looking for the ability to stream video from the blob storage.

But you have already achieved the uploading process?

**Comment by Elijah23Johnson** [comment]
In that case all you need to do is present the file in the app using [react-native Image](https://reactnative.dev/docs/image.html) or for [Video](https://github.com/react-native-community/react-native-video)

**Comment by Vrushabh59** [comment]
I also want to implement delete a blob from app. i am stucked here. How can i implement delete functionality.

**Comment by Elijah23Johnson** [comment]
The library currently does not support the delete operation. I except pull request. So the native modules will have to implement the delete operation for the respective Azure libs.

**Comment by sdhimanwyest** [comment]
Can you provide the download file code?

**Comment by Vrushabh59** [comment]
I had used different library for achieving functionality 
https://www.npmjs.com/package/react-native-azure-blob-storage-manager

**Comment by bambuzld** [comment]
Can you provide an example for downloading the file from Azure Blob Storage?
