### ISSUE TITLE
EAzureBlobStorageImage is null

### ISSUE THREAD

**Issue by ammedinap93** [Elijah23Johnson/react-native-azure-blob-storage#13]
I am using the example code given here:
https://www.npmjs.com/package/react-native-azure-blob-storage
![image](https://user-images.githubusercontent.com/43796884/93658383-1d36c600-fa09-11ea-9ba8-6fc8cb550489.png)
This code is not working for me, and the error is that EAzureBlobStorageImage object is always null, even inside componentDidMount method.
I am using Expo: Client version 2.16.1, Supported SDKs 35, 36, 37, 38.
Any help will be very appreciated.

**Comment by Elijah23Johnson** [comment]
This is a native module and is not be compatible with expo client. The library depends on native code for both Android and IOS.

**Comment by ammedinap93** [comment]
Thanks, I will use the library without Expo.
