### ISSUE TITLE
Is this library compatible with gradle 7.0?

### ISSUE THREAD

**Issue by ammedinap93** [Elijah23Johnson/react-native-azure-blob-storage#14]
I am trying the example code in a react native hello world project, but I got this error related to the library:
![image](https://user-images.githubusercontent.com/43796884/93737553-86593d80-fbb1-11ea-9ea3-a7be18ff0b69.png)
The message says:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Any help will be appreciated.

**Comment by ammedinap93** [comment]
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview

**Comment by Elijah23Johnson** [comment]
That error is bubbling up as a result of an assembly error more then likely and there is nothing wrong with your gradle. Do like the terminal say and run with the flags --warning-mode all. Pay attention to the terminal. 

Welcome to React Native...

**Comment by ammedinap93** [comment]
Thanks for the advice, it works fine now.
