### ISSUE TITLE
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by imsam67** [Elijah23Johnson/react-native-azure-blob-storage#15]
I'm following the code in the "Usage" section but running into issues. BTW, I'm on `"react-native": "0.63.2"` and `"react-native-azure-blob-storage": "^1.2.1"`

First, the error was `filePath` is not undefined. So, I created a variable and set its value like this
`const filePath = p.node.image.uri;`

This seems to get the uri to the image but when I select an image to upload to my Azure Blob Storage container, I get the following error. Any idea what's going on here and how to resolve this issue?
![Screenshot 2020-10-03 183446](https://user-images.githubusercontent.com/15844030/95004340-2302de80-05a7-11eb-8fc6-5fea0c0821f4.png)

**Comment by imsam67** [comment]
So, if I just pass the file path to `uploadFile()` method, it works fine and uploads the image. Any idea why in the Usage section of the documentation, it shows passing an object -- see below? Are we to pass a string to the `uploadFile()` method or an object?

![Screenshot 2020-10-03 184807](https://user-images.githubusercontent.com/15844030/95004492-17181c00-05a9-11eb-87ee-92ada59b2b5f.png)

**Comment by Elijah23Johnson** [comment]
Try like this EAzureBlobStorageFile.uploadFile(filePath)

It's a promise that will return the name of the uploaded file

**Comment by Elijah23Johnson** [comment]
Yea sure that was added on a PR and I haven't had the band width to publish that version... Testing etc. As other projects are more critical. Will update the readme.md until next version comes out. You can add a feature request and submit a PR if you have time. There are a lot of other option locked in the lib. Again just no time.

**Comment by imsam67** [comment]
@Elijah23Johnson Yes, passing only the file path works fine but the auto assigned file name doesn't have a file extension. So, in my Azure Blob Storage, I end up with a file named `prxujzyt` and not `prxujzyt.jpg`. I'm OK with the auto naming but making sure the blob has a file extension would be useful. Is there a way to this during upload or am I going to have to handle that after the upload by making an API call to Azure Blob Storage?

**Comment by Elijah23Johnson** [comment]
You actually don't need the ext. on the file name just to resolve the image. Azure will resolve it to azureedge.container/xdsdfadsf 
Here is an example of one that I uploaded 
https://garagedoorimages.blob.core.windows.net/doorimages/iiozanehrx
And it resolves fine not sure why you need the extension. The content type during upload sets it to  
image/png
--

**Comment by ankita-sinha-09** [comment]
Here what i did to work with this 
1. i cloned the project in project directory 
![image](https://user-images.githubusercontent.com/37877554/96442903-79b81b80-1229-11eb-9f96-9d9d00e1afa7.png)
Added Following code in FileManager.java for image SharedAccessBlobPolicy 
public static String UploadFile(InputStream image, int imageLength, String fileName, String contentType, String containerName) throws Exception {

        CloudBlobContainer container = getContainer(containerName);
        container.createIfNotExists();

        BlobContainerPermissions permissions = container.downloadPermissions();
        container.uploadPermissions(permissions);

        SharedAccessBlobPolicy sasPolicy = new SharedAccessBlobPolicy();
        GregorianCalendar calendar = new GregorianCalendar(TimeZone.getTimeZone("UTC"));
        calendar.add(Calendar.HOUR, 10);
        sasPolicy.setSharedAccessExpiryTime(calendar.getTime());

        sasPolicy.setPermissions(EnumSet.of(SharedAccessBlobPermissions.READ,
                SharedAccessBlobPermissions.WRITE,
                SharedAccessBlobPermissions.LIST));


        CloudBlockBlob imageBlob = container.getBlockBlobReference(fileName);
        imageBlob.getProperties().setContentType(contentType);
        imageBlob.upload(image, imageLength);
        String sas = imageBlob.generateSharedAccessSignature(sasPolicy, null);
        return imageBlob.getUri().toString() + "?" + sas;
    }

**Comment by rahulpandey** [comment]
Here what i did to work with this issue
I cloned this repo in project project directory then i added as local dependency 
![image](https://user-images.githubusercontent.com/1049467/96443537-68234380-122a-11eb-9eb6-7029a126576e.png)
add following code in FileManager.java to use with sas

public static String UploadFile(InputStream image, int imageLength, String fileName, String contentType, String containerName) throws Exception {

        CloudBlobContainer container = getContainer(containerName);
        container.createIfNotExists();

        BlobContainerPermissions permissions = container.downloadPermissions();
        container.uploadPermissions(permissions);

        SharedAccessBlobPolicy sasPolicy = new SharedAccessBlobPolicy();
        GregorianCalendar calendar = new GregorianCalendar(TimeZone.getTimeZone("UTC"));
        calendar.add(Calendar.HOUR, 10);
        sasPolicy.setSharedAccessExpiryTime(calendar.getTime());

        sasPolicy.setPermissions(EnumSet.of(SharedAccessBlobPermissions.READ,
                SharedAccessBlobPermissions.WRITE,
                SharedAccessBlobPermissions.LIST));


        CloudBlockBlob imageBlob = container.getBlockBlobReference(fileName);
        imageBlob.getProperties().setContentType(contentType);
        imageBlob.upload(image, imageLength);
        String sas = imageBlob.generateSharedAccessSignature(sasPolicy, null);
        return imageBlob.getUri().toString() + "?" + sas;
    }

**Comment by rahulpandey** [comment]
yes there is equivalent to in obejective c also 

    AZSCloudBlobClient *blobClient = [account getBlobClient];
    AZSSharedAccessBlobParameters *sp = [[AZSSharedAccessBlobParameters alloc] init];
    sp.storedPolicyIdentifier = @"readwrite";
    AZSSharedAccessPolicy *policy = [[AZSSharedAccessPolicy alloc] initWithIdentifier:sp.storedPolicyIdentifier];
    policy.permissions = AZSSharedAccessPermissionsRead|AZSSharedAccessPermissionsWrite;
    policy.sharedAccessExpiryTime = [[NSDate alloc] initWithTimeIntervalSinceNow:300];
    NSMutableDictionary *permissions = [NSMutableDictionary dictionaryWithDictionary:
                                        @{sp.storedPolicyIdentifier : policy}];
   
    AZSCloudBlobContainer *blobContainer = [blobClient containerReferenceFromName:containerName];
    [blobContainer uploadPermissions:permissions completionHandler:^(NSError *err) {
        if (err){
            reject(@"no_event",@"Error in creating container.",err);
        }else{
            __block NSError *error = nil;
            NSString *sasToken = [blobContainer createSharedAccessSignatureWithParameters:sp error:&error];
            AZSCloudBlockBlob *blockBlob = [blobContainer blockBlobReferenceFromName:fileName];
            blockBlob.properties.contentType = contentType;
            [blockBlob uploadFromFileWithURL:[NSURL URLWithString:filePath] completionHandler:^(NSError *err){
                if(err){
                    reject(@"no_event",[NSString stringWithFormat: @"Error in creating blob. %@",filePath],error);
                }else{
                    NSString *str = [NSString stringWithFormat: @"%@%@", blockBlob.storageUri.primaryUri, sasToken];
                    resolve(str);
                }
            }];
        }
        
    }];
