### ISSUE TITLE
Upload progress indicator to give user feedback

### ISSUE THREAD

**Issue by imsam67** [Elijah23Johnson/react-native-azure-blob-storage#16]
I like the fact that this solution focuses on the basics which is uploading files to Azure Blob Storage. Having said that it would be nice to show some type of upload progress bar to give user feedback. A typical progress bar with percentage of completion would do the trick.

**Comment by Elijah23Johnson** [comment]
Sure it would for now you can display a loading indicator when you start the upload and stop it when the name comes back.

**Comment by Elijah23Johnson** [comment]
Stale
