### ISSUE TITLE
Ios Error

### ISSUE THREAD

**Issue by blazerroad** [Elijah23Johnson/react-native-azure-blob-storage#2]
Hi, when i try it on IOs  this error happens : Error in creating blob , "No such file or directory"

**Comment by Elijah23Johnson** [comment]
Hi @blazerroad  would you mind sharing your implementation. So I can see what the problem is.

**Comment by Elijah23Johnson** [comment]
@blazerroad 
You have to remove **file://** from the front of the image path and only pass in **/pathtofile.png** 
> Ios requires a relative path Android Will work with either 
> EAzureBlobStorageImage.uploadFile('/Route To Image.PNG'')

**Comment by blazerroad** [comment]
I used what you shared as an example on your github  cameraroll return ph:// for IOS assests I even changed that to assesst-library:// but non of them work, the cameraroll does not return relative path file:// in IOS

**Comment by Elijah23Johnson** [comment]
Sorry to be more precise camera role returns an absolute path to the asset  so **file://..path/to/file.png** or **ph://..path/to/file.png**  you have to remove the file:// or ph:// and just pass in ..path/to/file.png

**Comment by Elijah23Johnson** [comment]
![image](https://user-images.githubusercontent.com/31963164/85205626-5c9e2b00-b2d1-11ea-8a2d-39bcce57d19b.png)

That is on of the implementations that I use. Notice the **replace** on the back of the expression. **response**  will contain the file path. although in this on I am using `react-native-image-picker`

![image](https://user-images.githubusercontent.com/31963164/85205703-d504ec00-b2d1-11ea-92d7-7c8042bc45d3.png)
