### ISSUE TITLE
Could not find a declaration file for module 'react-native-azure-blob-storage'. 

### ISSUE THREAD

**Issue by developeromI89** [Elijah23Johnson/react-native-azure-blob-storage#22]
Installed using npm i react-native-azure-blob-storage
When trying to use in .tsx file its giving declaration error.

Tried with installing types but it says @types/react-native-azure-blob-storage not exist

**Comment by Elijah23Johnson** [comment]
There is no types file in the repo.. PR welcome...

**Comment by vipulchakravarthy** [comment]
@developeromI89 There is no type files as @Elijah23Johnson mentioned.

Alternative approach could be create a @types folder in the root directory

Inside the @types folder, create a file with the name alltypes.d.ts and copy the below line inside it

`declare module 'react-native-azure-blob-storage'`

This worked for me. I hope it would help someone else too!

**Comment by Elijah23Johnson** [comment]
> @developeromI89 There is no type files as @Elijah23Johnson mentioned.
> 
> Alternative approach could be create a @types folder in the root directory
> 
> Inside the @types folder, create a file with the name alltypes.d.ts and copy the below line inside it
> 
> `declare module 'react-native-azure-blob-storage'`
> 
> This worked for me. I hope it would help someone else too!

Closing favor of @vipulchakravarthy response
