### ISSUE TITLE
Unknown argument type '__Bool' in method - [EAzureBlobStorageFile configure:key:container:token:] error

### ISSUE THREAD

**Issue by imsam67** [Elijah23Johnson/react-native-azure-blob-storage#40]
I'm testing my RN app using `react-native-azure-blob-storage` version `1.2.3` on iOS andI'm getting this error. I'm not getting it on Android. Any idea what may be causing it? BTW, the app is using React Native version `0.66.3`.
![Screenshot 2022-02-04 142049](https://user-images.githubusercontent.com/15844030/152624409-52076c21-0296-4eed-87cf-1596cefe2a52.png)

**Comment by shernandezp** [comment]
![image](https://user-images.githubusercontent.com/13307854/153318965-d2118019-087b-431e-a79a-3d5581c1f199.png)

**Comment by imsam67** [comment]
Still getting the error! This is only happening on iOS. It all works fine on Android.

**Comment by shernandezp** [comment]
My bad. What I did was introduce a controlled error, so that the application does not crash.
What I read is that it was an error in older versions of React-Native, prior to 0.60. I'm currently using v0.66.1, and the component does not work for iOs.
[https://stackoverflow.com/questions/66686710/unknown-argument-type-attribute-in-method-rctappstate-extend-rctconvert-t](url)
I will try to dig in a bit more on it, but unfortunately, I do have not much experience on iOs.

**Comment by Elijah23Johnson** [comment]
@shernandezp thanks for the input. 

This package is running on

```
 "devDependencies": {
    "react": "^16.8.3",
    "react-native": "^0.62.3"
  },
  
```
  So very likely there is a versioning problem. However revisiting the implementation
  
```
  RCT_EXPORT_METHOD(configure:(NSString *)account_name
         key:(NSString *)account_key
         container:(NSString *)conatiner_name
         token:(bool *)sas_token)
{
  ACCOUNT_NAME = account_name;
  ACCOUNT_KEY = account_key;
  CONTAINER_NAME = [conatiner_name lowercaseString];
  CONNECTION_STRING = [NSString stringWithFormat:@"DefaultEndpointsProtocol=https;AccountName=%@;AccountKey=%@",ACCOUNT_NAME,ACCOUNT_KEY];
  SAS = sas_token;
}
```

Please make sure that your passing a Boolean value for sasToken. 

Let me know how that works. Maybe try to hard code true in there or false. 

FALSE is not a valid Boolean

**Comment by imsam67** [comment]
@Elijah23Johnson I tried hard coding `true` and `false` in RN 0.66.3 and now RN 0.67.2 to no avail. Still getting the same error.

**Comment by matheusmhq** [comment]
Any solution?

**Comment by matheusmhq** [comment]
Some solution?

**Comment by matheusmhq** [comment]
Solution:

On path node_modules/react-native-azure-blob-storage/ios/EAzureBlobStorageFile.m

Change lines 8 and 120,  of "bool" to "BOOL"

![image](https://user-images.githubusercontent.com/36764886/166980993-82a5c2ee-19c1-462c-9291-db0b7dc105d3.png)
