### ISSUE TITLE
EAzureBlobStorageFile doesn't exist

### ISSUE THREAD

**Issue by aquastartw** [Elijah23Johnson/react-native-azure-blob-storage#9]
Miss EAzureBlobStorageFile in
https://github.com/Elijah23Johnson/react-native-azure-blob-storage#usage

**Comment by Elijah23Johnson** [comment]
You have to import it like so 
import { EAzureBlobStorageFile } from 'react-native-azure-blob-storage';

**Comment by alanko0202** [comment]
> You have to import it like so
> import { EAzureBlobStorageFile } from 'react-native-azure-blob-storage';

I have the same issue, using the react-native-azure-blob-storage (1.2.3)
import { EAzureBlobStorageImage, EAzureBlobStorageFile } from 'react-native-azure-blob-storage';
It is undefined for both EAzureBlobStorageImage, EAzureBlobStorageFile.

It is working fine for me to upload image in npm version 1.2.1

**Comment by SabyasachiP** [comment]
Not able to upload with  EAzureBlobStorageFile. Getting below exception.
undefined is not an object (evaluating '_reactNativeAzureBlobStorage.EAzureBlobStorageFile.uploadFile')
UploadFileToAzure$

**Comment by alanko0202** [comment]
> Not able to upload with EAzureBlobStorageFile. Getting below exception.
> undefined is not an object (evaluating '_reactNativeAzureBlobStorage.EAzureBlobStorageFile.uploadFile')
> UploadFileToAzure$

I had the same experience before. I made it works when changing the version to 1.2.1 in package.json
#12

**Comment by Elijah23Johnson** [comment]
See latest version and readme.md
